### ISSUE TITLE
[fixed] Mod crash with Aircraft mod plane crash

### ISSUE THREAD

**Issue by markhawrylak** [jocker-il/JKIL-KnightRider#7]
The mod causes an exception when using the Aircraft mod.   when the aircraft is destroyed due to biters, the following error is received:

The mod JKIL's KnightRider music while driving caused a non-recoverable error.
Please report this error to the mod author.

Error while running event JKIL-KnightRider::on_player_driving_changed_state (ID 26)
__JKIL-KnightRider__/control.lua:5: attempt to index field 'entity' (a nil value)
stack traceback:
	__JKIL-KnightRider__/control.lua:5: in function <__JKIL-KnightRider__/control.lua:3>

**Comment by markhawrylak** [comment]
The fix that was done 20 hours ago resolved it.
Awesome!,  I love the mod.

**Comment by jocker-il** [comment]
I'm still surprised is affecting the aircraft mod but I guess the aircraft is modeled from the car just without collisions...

 Glad the new version solves it 😊 and thank you for liking it
